name: z_chat
description: "A simple chat application, written in Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  riverpod_annotation: ^2.3.5
  riverpod: ^2.5.1
  go_router: ^14.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  go_router_builder: ^2.6.2
  build_verify: ^3.1.0

flutter:
  uses-material-design: true
